In [1]:
import numpy as np

In [7]:
nx, ny = (20,15)
x = np.linspace(0, 20, nx)
y = np.linspace(0, 15, ny)
xv, yv = np.meshgrid(x, y)

In [8]:
x

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [9]:
y

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

In [10]:
xv

array([[ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
         5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
        10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
        15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ],
       [ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
         5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
        10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
        15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ],
       [ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
         5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
        10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
        15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ],
       [ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
         5.26315789,  6.31578947,  7.36842105,  

In [11]:
yv

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
         1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
         1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
         1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857],
       [ 2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
         2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
         2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
         2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714],
       [ 3.21428571,  3.21428571,  3.21428571,  3.21428571,  3.21428571,
         3.21428571,  3.21428571,  3.21428571,  

In [12]:
print(xv.shape,'\n',yv.shape)

(15, 20) 
 (15, 20)


In [13]:
xv.ravel()

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ,
        0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ,
        0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ,
        0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47

In [14]:
yv.ravel()

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
        1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
        1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
        1.07142857,  1.07142857,  1.07142857,  1.07142857,  1.07142857,
        2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
        2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
        2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
        2.14285714,  2.14285714,  2.14285714,  2.14285714,  2.14285714,
        3.21428571,  3.21428571,  3.21428571,  3.21428571,  3.21428571,
        3.21428571,  3.21428571,  3.21428571,  3.21428571,  3.21

In [15]:
np.c_[xv.ravel(),yv.ravel()]

array([[ 0.        ,  0.        ],
       [ 1.05263158,  0.        ],
       [ 2.10526316,  0.        ],
       [ 3.15789474,  0.        ],
       [ 4.21052632,  0.        ],
       [ 5.26315789,  0.        ],
       [ 6.31578947,  0.        ],
       [ 7.36842105,  0.        ],
       [ 8.42105263,  0.        ],
       [ 9.47368421,  0.        ],
       [10.52631579,  0.        ],
       [11.57894737,  0.        ],
       [12.63157895,  0.        ],
       [13.68421053,  0.        ],
       [14.73684211,  0.        ],
       [15.78947368,  0.        ],
       [16.84210526,  0.        ],
       [17.89473684,  0.        ],
       [18.94736842,  0.        ],
       [20.        ,  0.        ],
       [ 0.        ,  1.07142857],
       [ 1.05263158,  1.07142857],
       [ 2.10526316,  1.07142857],
       [ 3.15789474,  1.07142857],
       [ 4.21052632,  1.07142857],
       [ 5.26315789,  1.07142857],
       [ 6.31578947,  1.07142857],
       [ 7.36842105,  1.07142857],
       [ 8.42105263,

In [16]:
(np.c_[xv.ravel(),yv.ravel()]).shape

(300, 2)